### ISSUE TITLE
Fix code scanning alert - Unchecked transfer - Use SafeERC20

### ISSUE THREAD

**Issue by JustInPosition** [PositionExchange/position-protocol#79]
Tracking issue for:
- [x] https://github.com/PositionExchange/position-protocol/security/code-scanning/4

*TODO*

Use SafeERC20

**Comment by MusketPosition** [comment]
> Tracking issue for:
> 
> * [x]  [Unchecked transfer](/PositionExchange/position-protocol/security/code-scanning/4)
> 
> _TODO_
> 
> Use SafeERC20

@JustInPosition pls review the pull request [#85](https://github.com/PositionExchange/position-protocol/pull/85)
