### ISSUE TITLE
Fix code scanning alert - Missing events arithmetic

### ISSUE THREAD

**Issue by JustInPosition** [PositionExchange/position-protocol#80]
Tracking issue for:
- [x] https://github.com/PositionExchange/position-protocol/security/code-scanning/41

**Comment by decusio** [comment]
hello dev I've reported the vulnerability
 sqlinjection and to contact@position.exchange have not been fixed. and have not received a reply

**Comment by JustInPosition** [comment]
Hi @decusio, please report it to https://immunefi.com/bounty/positionexchange/

As contact@position.exchange is only used for supporting

**Comment by MusketPosition** [comment]
> Tracking issue for:
> 
> * [x]  [Missing events arithmetic](/PositionExchange/position-protocol/security/code-scanning/41)

@JustInPosition pls review the pull request  [#84](https://github.com/PositionExchange/position-protocol/pull/84)
